### ISSUE TITLE
Padronizar espaçamento

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/blog#1]
Não existe um padrão de espaçamento. Ver [este](https://github.com/bbatsov/ruby-style-guide#layout) arquivo, por exemplo.

Seguimos [esse](https://github.com/bbatsov/ruby-style-guide#layout) padrão de estilo.

**Comment by tacsio** [comment]
Corrigido padrão de espaçamento (2 espaços por tab) em 2e8012b60af2b036ce4a3f8a

Verifiquei os outros arquivos e não identifiquei mais tab's fora da formatação.
