### ISSUE TITLE
Imagens de avatar dos membros da seção "Quem Somos" em desalinho com seus nomes.

### ISSUE THREAD

**Issue by embs** [redu/blog#14]
![avatar desalinhado](http://img6.imagebanana.com/img/vhw09lef/Seleo_001.png)

**Comment by thaisbione** [comment]
https://github.com/redu/blog/commit/8db6d2d9f332eb91067bc0e921a01347faee2681

Matheus, aí está o commit com a modificão. Ao meu ver, o problema foi resolvido. Mas, qualquer coisa é só falar.
