### ISSUE TITLE
Otimizar PNGs

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/blog#16]
Notei que alguns png não estão otimizados o suficiente. Sugiro usar Page Speed (plugin do chrome) para analisar isso.

**Comment by julianalucena** [comment]
Como assim não estão o suficiente, @guiocavalcanti ? Isso pode acontecer mesmo usando o optipng ou deve ter sido esquecimento?

**Comment by guiocavalcanti** [comment]
Acho nem todos foram otimizados. Commitei.

**Comment by julianalucena** [comment]
Okey dokey.
