### ISSUE TITLE
Atualizar Rails

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/blog#24]
Mais informações https://gemnasium.com/redu/blog

**Comment by guiocavalcanti** [comment]
@embs, você pode fazer o upgrade?

**Comment by embs** [comment]
@guiocavalcanti, as modificações na maneira como os parâmetros são parseados na nova versão do Rails fizeram com que o [helper que utilizamos para seleção de tags](https://github.com/redu/blog/blob/master/app/views/posts/_use_tag.html.erb#L2) mandasse o primeiro elemento do array de tags sempre vazio. Por exemplo, quando não são selecionadas tags, o controlador recebe:

``` ruby
"id" => [""]
```

e quando são selecionadas tags:

``` ruby
"id" => ["", "1", "2"]
```

Pesquisei um pouco por uma maneira alternativa de fazer o select mas estava perdendo muito tempo com isso (não fui eu quem implementou originalmente a funcionalidade) e por isso acabei resolvendo de um jeito quick and dirty. Tens uma ideia melhor pra resolver esse problema?

**Comment by guiocavalcanti** [comment]
@embs essa maneira está boa, só imaginei algo como `["1", "", "3"].reject(&:blank?).collect(&:to_i)` para fazer essa filtragem.

**Comment by embs** [comment]
@guiocavalcanti, modifico? A maneira como fiz me parece mais limpa / enxuta.

**Comment by guiocavalcanti** [comment]
Pode deixar dessa forma.

## 

Guilherme Cavalcanti
+55 81 9194 5317
http://twitter.com/guiocavalcanti
http://linkedin.com/in/guiocavalcanti

**Comment by julianalucena** [comment]
Estranho, no https://gemnasium.com/redu/blog ainda aparece a versão incorreta.

**Comment by julianalucena** [comment]
Tu deu deploy no heroku?

**Comment by julianalucena** [comment]
Apertei no botão de reabrir sem querer. :smile:

**Comment by embs** [comment]
Dei deploy.
